listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

rtc_server {
    enabled         off;
}

vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency     on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr              off;
    }

    hls {
        enabled         off;
        hls_path        ./objs/nginx/html;
        hls_fragment    2;
        hls_window      10;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    dvr {
        enabled     on;
        dvr_path    /tmp/golive/records/[stream].flv;
        dvr_plan    session;
    }
    http_hooks {
        enabled         on;
        on_publish      http://room-service:8091/srs/on_publish;
        on_unpublish    http://room-service:8091/srs/on_unpublish;
    }
    exec {
        enabled         off;
    }
}
